### ISSUE TITLE
OS Site is Empty

### ISSUE THREAD

**Issue by justinelsberry** [47deg/47deg.github.io#5]
HELP! Going to the OS site is shows no projects or stars or anything!! Looks like a bad merge.

https://47deg.github.io

**Comment by suhasgaddam** [comment]
GET https://api.github.com/orgs/47deg/repos?type=public&per_page=100
```
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```

https://github.com/47deg/47deg.github.io/blob/master/index.html#L1
https://github.com/47deg/47deg.github.io/blob/master/index.html#L5

**Comment by dominv** [comment]
I've already restored the site to the last working commit and the content is being shown again. 
It seems that although this build https://travis-ci.org/47deg/org/builds/244985961 has failed generating the site correctly (because of an issue that it's already being investigating in https://github.com/47deg/org/issues/60), it has deployed the site.
